"""add content

Revision ID: 090fb6f5bb45
Revises: a18b2b45216b
Create Date: 2021-09-28 01:15:52.486026

"""
from alembic import op
import sqlalchemy as sa
from core.database import Base


# revision identifiers, used by Alembic.
revision = '090fb6f5bb45'
down_revision = 'a18b2b45216b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('content', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'content')
    # ### end Alembic commands ###
