"""Rename read_length to read_time

Revision ID: 1e0c0d4f51f6
Revises: 9150a2b603d9
Create Date: 2021-10-17 13:56:31.265803

"""
from alembic import op
import sqlalchemy as sa
from core.base import Base


# revision identifiers, used by Alembic.
revision = '1e0c0d4f51f6'
down_revision = '9150a2b603d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('read_time', sa.Integer(), nullable=True))
    op.drop_column('posts', 'read_length')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('read_length', sa.INTEGER(), nullable=True))
    op.drop_column('posts', 'read_time')
    # ### end Alembic commands ###
