"""test string

Revision ID: 2a38977b96be
Revises: 090fb6f5bb45
Create Date: 2021-09-28 20:37:32.313362

"""
from alembic import op
import sqlalchemy as sa
from core.database import Base


# revision identifiers, used by Alembic.
revision = '2a38977b96be'
down_revision = '090fb6f5bb45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('ta', sa.String(length=25), nullable=True))
    op.add_column('post', sa.Column('te', sa.String(), nullable=True))
    op.add_column('post', sa.Column('ti', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'ti')
    op.drop_column('post', 'te')
    op.drop_column('post', 'ta')
    # ### end Alembic commands ###
