"""Category Updated Field

Revision ID: 3bf88ef219e3
Revises: dcf28a4a378b
Create Date: 2021-10-09 21:23:03.998592

"""
from alembic import op
import sqlalchemy as sa
from core.base import Base


# revision identifiers, used by Alembic.
revision = '3bf88ef219e3'
down_revision = 'dcf28a4a378b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
