"""Removed Cascade

Revision ID: 40f0ee5383ef
Revises: 507a013e929a
Create Date: 2021-10-12 22:17:23.665538

"""
from alembic import op
import sqlalchemy as sa
from core.base import Base


# revision identifiers, used by Alembic.
revision = '40f0ee5383ef'
down_revision = '507a013e929a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
