"""Add nullable to time fields

Revision ID: 48245b4ab25a
Revises: 40f0ee5383ef
Create Date: 2021-10-13 18:55:59.264251

"""
from alembic import op
import sqlalchemy as sa
from core.base import Base


# revision identifiers, used by Alembic.
revision = '48245b4ab25a'
down_revision = '40f0ee5383ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
