"""Add Cascade

Revision ID: 507a013e929a
Revises: 29ab561fd33d
Create Date: 2021-10-12 22:04:01.806519

"""
from alembic import op
import sqlalchemy as sa
from core.base import Base


# revision identifiers, used by Alembic.
revision = '507a013e929a'
down_revision = '29ab561fd33d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
