"""Category Updated Field

Revision ID: 9e56356a845a
Revises: 3bf88ef219e3
Create Date: 2021-10-09 21:27:38.917645

"""
from alembic import op
import sqlalchemy as sa
from core.base import Base


# revision identifiers, used by Alembic.
revision = '9e56356a845a'
down_revision = '3bf88ef219e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
