"""Update category time

Revision ID: fa5df05b8595
Revises: 9e56356a845a
Create Date: 2021-10-10 16:05:54.996293

"""
from alembic import op
import sqlalchemy as sa
from core.base import Base


# revision identifiers, used by Alembic.
revision = 'fa5df05b8595'
down_revision = '9e56356a845a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
